#!/usr/bin/env bash

case "$(uname -s)" in
    Darwin*)    open=open;;
    Linux*)     open=xdg-open;;
esac

LANGUAGE=$1

if [[ ${LANGUAGE} == ru ]]; then
    ENGINE=-pdflua
else
    ENGINE=-pdf
fi

# rm triggers latexmk build even if previous artifacts generated by faulty run of po4a prevent it from running
rm -f main_${LANGUAGE}.aux && \
  po4a --no-update po4a.cfg && \
  latexmk ${ENGINE} -shell-escape main_${LANGUAGE}.tex
${open} main_${LANGUAGE}.pdf &
