#!/usr/bin/env bash

source tools/.language_base.sh

# Default values
SECTION_SEARCH=""

# Function to print usage information
usage() {
  echo "Usage: $0 [language] [-p|--printable] [-n|--no-bg] [-s|--section SEARCH] [--args ARGUMENTS]"
  echo "Example: $0 fr --printable --no-bg"
  echo
  echo "Positional arguments:"
  echo "  language           Language code (${valid_languages[*]})"
  echo "                     Defaults to 'en' if not specified"
  echo
  echo "Options:"
  echo "  -p, --printable    Enable printable mode"
  echo "  -n, --no-bg        Disable background"
  echo "  -s, --section      Build a single section matching the input given"
  echo "  --args             Additional arguments to pass to the LaTeX compiler (e.g., \"-silent\")"
  exit 1
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    -p|--printable)
        export HOMM3_PRINTABLE=1
        shift
        ;;
    -n|--no-bg)
        export HOMM3_NO_ART_BACKGROUND=1
        shift
        ;;
    -s|--section)
        shift
        if [[ $# -lt 1 ]]; then
          echo "Error: -s|--section requires a string argument" >&2
          usage
        fi
        SECTION_SEARCH="$1"
        shift
        ;;
    --args)
        shift
        if [[ $# -lt 1 ]]; then
          echo "Error: --args requires an argument" >&2
          usage
        fi
        ARGS="$1"
        shift
        ;;
    -h|--help)
        usage
        ;;
    -*)
        echo "Error: Unknown option $1" >&2
        usage
        ;;
    *)
        echo "Error: Unexpected argument '$1'" >&2
        usage
        ;;
  esac
done

case "$(uname -s)" in
  Darwin*)
    open=open
    ;;
  Linux*)
    open=xdg-open
    ;;
  MINGW*|MSYS*|CYGWIN*)
    open=start
    ;;
esac

TEMP_DIR=$(mktemp -d)
cleanup() {
  if [[ -n "${TEMP_STRUCTURE}" ]]; then
    cp "$TEMP_STRUCTURE" structure.tex 2> /dev/null
  fi
  rm -rf "$TEMP_DIR"
}

trap cleanup EXIT
if [[ -n "${SECTION_SEARCH}" ]]; then
  TARGET=$(grep "include{" structure.tex | grep "$SECTION_SEARCH")

  # Target is empty
  if [[ -z "$TARGET" ]]; then
    echo "Error: No section found matching '$SECTION_SEARCH'" >&2
    exit 1
  fi

  # Target is ambiguous
  if [[ $(echo "$TARGET" | wc -l) -gt 1 ]]; then
    echo "Error: Multiple sections found matching '$SECTION_SEARCH':" >&2
    echo "$TARGET" >&2
    exit 1
  fi

  TEMP_STRUCTURE=$(mktemp "$TEMP_DIR/structure.XXXXXX")
  cp structure.tex "$TEMP_STRUCTURE"
  echo "$TARGET" > structure.tex
  TARGET=$(echo "$TARGET" | grep -Po "[a-z_]*${SECTION_SEARCH}[a-z_]*")
fi

if [[ ${LANGUAGE} != en ]]; then
  PO4A_PATH="po4a.cfg"
  if [[ -n "${SECTION_SEARCH}" ]]; then
    # limit po4a run to a single section
    temp_po4a_file=$(mktemp "$TEMP_DIR/po4a.XXXXXX")
    grep -v "\[type:" "$PO4A_PATH" > "$temp_po4a_file"
    grep "language_metadata" "$PO4A_PATH" >> "$temp_po4a_file"
    grep "$TARGET" "$PO4A_PATH" >> "$temp_po4a_file"
    PO4A_PATH=$temp_po4a_file
  fi
  # limit output to specified language
  if ! po4a --no-update "$PO4A_PATH" --target-lang "${LANGUAGE}"; then
    echo -e "---\npo4a failed for language ${LANGUAGE}, please fix the errors."
    find translations -name "$LANGUAGE.po" -type f -exec msgfmt -c --check-format -o /dev/null '{}' \;
    exit 1
  fi
fi

if [[ "${SECTION_SEARCH}" == "" || "${LANGUAGE}" != "en" ]]; then
  # rm triggers latexmk build even if previous artifacts generated by faulty run of po4a prevent it from running
  rm -f "main_${LANGUAGE}.aux"
fi
latexmk -pdflua -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape -recorder $ARGS "main_${LANGUAGE}.tex"
${open} "main_${LANGUAGE}.pdf" &> /dev/null &

echo "main_${LANGUAGE}.pdf"
