name: Build Components List

on:
  pull_request:
    branches: [main]
    paths:
      - 'assets/**'
      - '!assets/gimp-files/**'
      - 'components_list.tex'
      - 'components_lists/**'

jobs:
  build_components_list:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          extra_system_packages: "inkscape"
          root_file: components_list.tex
          latexmk_shell_escape: true
