name: Build Components List

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - "assets/gimp-files/**"
      - "sections/**"
      - .gitignore
      - .pre-commit-config.yaml
      - README.md
      - main.tex
      - make_printable.sh

jobs:
  build_components_list:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          extra_system_packages: "inkscape"
          root_file: components_list.tex
          latexmk_shell_escape: true

      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: COMPONENTS_LIST_PDF
          path: components_list.pdf
