name: Check for unupdated translations

on:
  pull_request:
    branches: [main]

jobs:
  check_po4a:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Run po4a
        uses: qwrtln/po4a-action@v1
        with:
          version: "0.73"
          config: "po4a.cfg"
          args: "--no-translations"

      - name: Check if translations require updating
        run: |
          if [[ `git status --porcelain translations` ]]; then
            echo "There are uncommited changes to translations:"
            git status --porcelain translations
            exit 1
          fi
