name: Check for unpdated translations


on:
  pull_request:
    branches: [main]
    paths:
      - 'assets/**'
      - '!assets/gimp-files/**'
      - '**.tex'
      - 'translations/**'

  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: read
  pull-requests: write
  id-token: 'write'
  statuses: write

env:
  PO4A_VERSION: "0.71"
  PO4A_GH_URL: https://github.com/mquinson/po4a/releases/download

jobs:
  check_po4a:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Install po4a
        run: |
          sudo apt-get install -y po4a  # required as standalone po4a is missing some deps
          wget --quiet ${{ env.PO4A_GH_URL }}/v${{ env.PO4A_VERSION }}/po4a-${{ env.PO4A_VERSION}}.tar.gz  # sadly the version from apt isn't working
          export PO4A_DIR="po4a-${{ env.PO4A_VERSION }}"
          tar -xf ${PO4A_DIR}.tar.gz

      - name: Check if translations require updating
        run: |
          export PO4A_DIR="po4a-${{ env.PO4A_VERSION }}"
          export PERL5LIB="${PO4A_DIR}/lib:${PERL5LIB}"
          ./${PO4A_DIR}/po4a -v po4a.cfg
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            echo "There are uncommited changes to translations:"
            git status --porcelain | grep -v po4a
            echo "Please run 'po4a po4a.cfg' and commit them."
            exit 1
          fi

  get-comment:
    name: Get po4a check comment
    if: (github.event.issue.pull_request && startsWith(github.event.comment.body, 'po4a check'))
    runs-on: ubuntu-latest

    steps:
      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Add comment
        run: gh pr comment ${{ steps.comment-branch.outputs.head_ref }} --body "Hi from po4a"
