name: Check for unupdated translations

on:
  pull_request:
    branches: [main]

jobs:
  check_po4a:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Run po4a
        uses: qwrtln/po4a-action@v1
        with:
          version: "0.73"
          config: "po4a.cfg"
          args: "--no-translations"

      - name: Check if translations require updating
        run: |
          if [[ `git status --porcelain translations` ]]; then
            echo "There are uncommited changes to translations:"
            git status --porcelain translations
            git diff | tee po4a.patch
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: po4a-patch
          path: po4a.patch
          retention-days: 1
          if-no-files-found: ignore
